### ISSUE TITLE
Introduce debugging flags

### ISSUE THREAD

**Issue by viktormalik** [diffkemp/diffkemp#238]
We have flags to increase verbosity, but those are not sufficient when debugging DiffKemp, especially the compare phase. It would be good to introduce debugging outputs and flags for controlling it. The flags should offer ways to control at least:

- verbosity (level) of debugging (e.g. `-d`, `-dd` or `--debug-level N`)
- part which should be debugged (comparator, patterns, all, etc.).

This could possibly replace the [custom GDB script](https://github.com/viktormalik/diffkemp/blob/master/tools/func_comparator_return_vals.gdb) that we use to debug `DifferentialFunctionComparator`.

**Comment by FrNecas** [comment]
Resolved by https://github.com/diffkemp/diffkemp/pull/256
