### ISSUE TITLE
Tests for build command

### ISSUE THREAD

**Issue by lenticularis39** [diffkemp/diffkemp#245]

**Comment by PLukas2018** [comment]
Tests for build command were added in #324 and #326.

Tests for `llvm-to-snapshot` command and tests for methods of classes located in [`diffkemp/llvm_ir`](https://github.com/diffkemp/diffkemp/tree/master/diffkemp/llvm_ir) (for `diffkemp/llvm_ir/kernel_llvm_source_builder.py` and `diffkemp/llvm_ir/kernel_source_tree.py` tests exist) could be added .
