### ISSUE TITLE
Separate and enhance development guide

### ISSUE THREAD

**Issue by viktormalik** [diffkemp/diffkemp#296]
The development + tests sections of README are getting quite long, especially if we merge Nix support (#294). In addition, they are missing some information (packages necessary for building kernels, basic developer guidelines, etc.).

Therefore, it makes sense to extend these parts and move them into a separate document (e.g. `docs/development.md`).

**Comment by PLukas2018** [comment]
Solved by #346, the development guide is located in `docs/development.md`, and contains info about
- How to set up development,
- How to build,
- How to check code follows the coding,
- Where the tests are located and how to run, 
- Links to tools for performing,
- Useful links to learn more.
