### ISSUE TITLE
Write Quick start guide

### ISSUE THREAD

**Issue by viktormalik** [diffkemp/diffkemp#297]
It would be nice to have some sort of a quick start guide which would contain basics steps for building and running DiffKemp for various common scenarios and setting up basic development environment.

Probably makes sense to wait until #294 is merged.

**Comment by PLukas2018** [comment]
Solved by #346, the `docs/examples/` directory contains examples trying to show and explain how DiffKemp can be used.
The directory contains three examples showing how to use DiffKemp :
- on a very simple program (containing a few lines of code),
- on the musl C library,
- on the kernels.
