### ISSUE TITLE
Missing pip requirement in RPM package

### ISSUE THREAD

**Issue by PLukas2018** [diffkemp/diffkemp#334]
I tried to install DiffKemp on Fedora (in docker) from the RPM package and it looks like that the specification is missing `pip` as a requirement.

I used the following commands for installation:

```bash
dnf install -y dnf-plugins-core
dnf copr enable -y viktormalik/diffkemp
dnf install -y diffkemp
```

The installation is successful but when I run `diffkemp -h` error is thrown:
```bash
Traceback (most recent call last):
  File "/usr/bin/diffkemp", line 3, in <module>
    from diffkemp import diffkemp
  File "/usr/lib64/python3.11/site-packages/diffkemp/diffkemp.py", line 3, in <module>
    from diffkemp.config import Config
  File "/usr/lib64/python3.11/site-packages/diffkemp/config.py", line 3, in <module>
    from diffkemp.snapshot import Snapshot
  File "/usr/lib64/python3.11/site-packages/diffkemp/snapshot.py", line 14, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
```

After installing pip with `dnf install -y pip` it works.

**Comment by FrNecas** [comment]
`pkg_resources` comes from the `setuptools` package. I see that we have setuptools in the BuildRequires:

https://github.com/diffkemp/diffkemp/blob/e6cded9aefd2e51ada26c972f499fe08d442d789/rpm/diffkemp.spec#L14

Looks like that it should also be in `Requires` since it is also a runtime dependency.

**Comment by PLukas2018** [comment]
The problem was not encountered when trying it in normal Fedora (not in docker).
